### ISSUE TITLE
为什么我运行到手机的时候是 空白的呢？？

### ISSUE THREAD

**Issue by tianshaokai** [fengjundev/DoubanMovie-React-Native#1]

**Comment by fengjundev** [comment]
能详细描述下吗

**Comment by tianshaokai** [comment]
我是在ubuntu 里运行的，把代码下载了下来，开了两个命令窗口一个执行 react-native start ，另一个执行 react-native run-android 命令，打包成apk 安装到手机的时候，都是空白的，不显示页面和数据。

**Comment by fengjundev** [comment]
1. 先尝试把所有终端窗口关闭，包括过程中启动的server的窗口
2. 跑下`npm install`安装所有依赖
3. 再连接USB执行`react-native run-android`进行安装，点击menu在`dev-settings`中设置ip为你pc的ip

try it 😃

**Comment by tianshaokai** [comment]
我都是从新npm 安装的，  点击menu在dev-settings中设置ip为你pc的ip 这句话是什么意思呢？？ 是不是我安装的环境有问题啊？

**Comment by fengjundev** [comment]
如果使用真机调试的话，需要设置app中的js server的ip地址，指向你的pc，而且手机和pc需要在同一个网络中，如果是使用虚拟机就不用去设置这个了

设置可以看[这里](https://facebook.github.io/react-native/docs/running-on-device-android.html)

**Comment by tianshaokai** [comment]
哦哦，如果要是发布apk 的话，这样大家都不能设置的啊

**Comment by fengjundev** [comment]
需要发布APK的话需要进行打包，这时APP运行不再从 Debug Server 获取资源，而是通过asset下打包好的js.bundle读取
